export { default as MainSlider } from './MainSlider';
export { default as MainFeature } from './MainFeature';
export { default as GetQuote } from './GetQuote';
export { default as FeatureSlider } from './FeatureSlider';
export { default as Blogs } from './Blogs';
export { default as Quotation } from './Quotation';
export { default as Gallery } from './Gallery';
export { default as About } from './About';
export { default as ClientLogo } from './ClientLogo';
